apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - datasources-configmap.yaml

configMapGenerator:
  - name: grafana-dashboards
    files:
      - provisioning/dashboards/dashboard-provider.yaml
#      - provisioning/dashboards/microservices-dashboard.json
#      - provisioning/dashboards/database-dashboard.json
      - provisioning/dashboards/Docker-Desktop.json
      - provisioning/dashboards/Java-service.json
      - provisioning/dashboards/Kafka.json
      - provisioning/dashboards/Postgres-and-Redis.json