apiVersion: v1
kind: Service
metadata:
  name: balance-postgres
spec:
  type: NodePort  # Для доступа снаружи
  selector:
    app: balance-postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30033  # Будет доступен на localhost:30300