apiVersion: apps/v1
kind: Deployment
metadata:
  name: balance-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: balance-service
  template:
    metadata:
      labels:
        app: balance-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: balance-service
          image: chizhovvm/balance-service:latest
          imagePullPolicy: Always  # Всегда тянет новую версию IfNotPresent - только конкретную
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: SERVER_PORT
              value: "8082"
            - name: SPRING_FLYWAY_ENABLED
              value: "true"
            - name: SPRING_FLYWAY_BASELINE_ON_MIGRATE
              value: "true"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://balance-postgres:5432/balance_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "balance_user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "balance_password"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-broker:9092"
            - name: SPRING_REDIS_HOST
              value: "redis"
            - name: SPRING_REDIS_PORT
              value: "6379"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 90  # Даем время на запуск Spring Boot
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"