apiVersion: v1
kind: Service
metadata:
  name: balance-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8082"
spec:
  type: NodePort  # Для доступа извне (Postman)
  selector:
    app: balance-service
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082  # Будет доступен на localhost:30082