apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-postgres
  template:
    metadata:
      labels:
        app: notification-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: "notification_db"
            - name: POSTGRES_USER
              value: "notification_user"
            - name: POSTGRES_PASSWORD
              value: "notification_password"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: notification-postgres-pvc