apiVersion: v1
kind: Service
metadata:
  name: notification-postgres
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
spec:
  type: NodePort  # Для доступа снаружи
  selector:
    app: notification-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      nodePort: 30034  # Будет доступен на localhost:30034

    - name: metrics
      port: 9187
      targetPort: 9187