apiVersion: v1
kind: Service
metadata:
  name: notification-postgres
spec:
  type: NodePort  # Для доступа снаружи
  selector:
    app: notification-postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30034  # Будет доступен на localhost:30300