apiVersion: v1
kind: Service
metadata:
  name: payment-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
spec:
  type: NodePort  # Для доступа извне
  selector:
    app: payment-service
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081  # Будет доступен на localhost:30081